name: 提交 Bug
description: 在使用 轻量工具箱 过程中遇到了问题
title: "[Bug]: "
labels: ["bug"]

body:
  - type: textarea
    id: reproduce-steps
    attributes:
      label: 重现步骤
      description: |
        我们需要执行哪些操作才能让 Bug 出现？
        简洁清晰的重现步骤能够帮助我们更迅速地定位问题所在。
    validations:
      required: true