name: 优化提议
description: 对已有功能进行增强或调整
title: '[Feat]: '
labels: [ "enhancement" ]

body:
  - type: textarea
    id: feature-to-add
    attributes:
      label: 需要调整的功能内容
      description: |
        请具体提出想添加的功能，包括实现的模拟（如有）
        是否有类似的功能已经实现？如有请肯定地提出与该功能不同的地方/想改进/添加该功能的哪一部分。
    validations:
      required: true
